/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StaticFormImport } from './routes/static-form'
import { Route as DynamicFormImport } from './routes/dynamic-form'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StaticFormRoute = StaticFormImport.update({
  id: '/static-form',
  path: '/static-form',
  getParentRoute: () => rootRoute,
} as any)

const DynamicFormRoute = DynamicFormImport.update({
  id: '/dynamic-form',
  path: '/dynamic-form',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dynamic-form': {
      id: '/dynamic-form'
      path: '/dynamic-form'
      fullPath: '/dynamic-form'
      preLoaderRoute: typeof DynamicFormImport
      parentRoute: typeof rootRoute
    }
    '/static-form': {
      id: '/static-form'
      path: '/static-form'
      fullPath: '/static-form'
      preLoaderRoute: typeof StaticFormImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dynamic-form': typeof DynamicFormRoute
  '/static-form': typeof StaticFormRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dynamic-form': typeof DynamicFormRoute
  '/static-form': typeof StaticFormRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dynamic-form': typeof DynamicFormRoute
  '/static-form': typeof StaticFormRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dynamic-form' | '/static-form'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dynamic-form' | '/static-form'
  id: '__root__' | '/' | '/dynamic-form' | '/static-form'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DynamicFormRoute: typeof DynamicFormRoute
  StaticFormRoute: typeof StaticFormRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DynamicFormRoute: DynamicFormRoute,
  StaticFormRoute: StaticFormRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dynamic-form",
        "/static-form"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dynamic-form": {
      "filePath": "dynamic-form.tsx"
    },
    "/static-form": {
      "filePath": "static-form.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
